---
schemaVersion: 4.81
defaults:
  archiveDirectory: sysmon #Name of directories at volume roots into which copy-on-delete files are moved. The directory is protected with a System ACL (you can use PsExec from Sysinternals to access the directory using psexec -sid cmd). Default: Sysmon
  checkRevocation: true #Controls signature revocation checks. Default: True
  copyOnDeleteExtensions: #Extensions for files that are preserved on delete.
  copyOnDeletePE:  #Preserves deleted executable image files. Default: False
  copyOnDeleteProcesses: #Process name(s) for which file deletes will be preserved.
  copyOnDeleteSIDs: #Comma-separated list of account SIDs for which file deletes will be preserved.
  dnsLookup: true #Controls reverse DNS lookup. Default: True
  driverName: #Uses specied name for driver and service images.
  hashAlgorithms: #Hash algorithm(s) to apply for hashing. Algorithms supported include MD5, SHA1, SHA256, IMPHASH and * (all). Default: None
  - MD5
  - SHA256
  - IMPHASH 
outFilename: out/sysmon-config-sample.xml
eventFilter:
eventFilter:
  - eventName: ProcessCreate
    include: false
    exclude: true
  - eventName: FileCreateTime
    include: true
    exclude: true
  - eventName: NetworkConnect
    include: false
    exclude: true
  - eventName: ProcessTerminate
    include: true
    exclude: true
  - eventName: DriverLoad
    include: false
    exclude: true
  - eventName: ImageLoad
    include: true
    exclude: true
  - eventName: CreateRemoteThread
    include: false
    exclude: true
  - eventName: RawAccessRead
    include: true
    exclude: false
  - eventName: ProcessAccess
    include: true
    exclude: true
  - eventName: FileCreate
    include: true
    exclude: true
  - eventName: RegistryEvent
    include: true
    exclude: true
  - eventName: FileCreateStreamHash
    include: true
    exclude: true
  - eventName: PipeEvent
    include: false
    exclude: true
  - eventName: WmiEvent
    include: false
    exclude: true
  - eventName: DnsQuery
    include: false
    exclude: true
  - eventName: FileDelete
    include: true
    exclude: false
  - eventName: ClipboardChange
    include: true
    exclude: false
  - eventName: ProcessTampering
    include: false
    exclude: true
  - eventName: FileDeleteDetected
    include: true
    exclude: true
modulesBasePath: modules/
modules:
  - module-example.xml
  - module-example_2.xml