package main

import (
	"fmt"
	"log"
	"time"

	"github.com/Che4ter/go-sysmon-configurator/config"
	"github.com/Che4ter/go-sysmon-configurator/helper"
	"github.com/Che4ter/go-sysmon-configurator/sysmon"
)

const SchemaVersion = 4.81

var Version = "dev build"

func main() {
	fmt.Println("Sysmon Configurator - Version " + Version)

	cfgPath, generateRuleIds, removeRuleNames, err := config.ParseFlags()
	if err != nil {
		log.Fatal(err)
	}
	cfg, err := config.LoadConfig(cfgPath)
	if err != nil {
		log.Fatal(err)
	}

	sysmonBaseConfig, err := config.GenerateBaseSysmonConfig(*cfg, SchemaVersion)
	if err != nil {
		log.Fatal(err)
	}

	sysmonModules, err := sysmon.LoadSysmonModules(cfg.ModulesBasePath, cfg.Modules)
	if err != nil {
		log.Fatal(err)
	}

	err = sysmon.MergeModulesWithBaseConfig(sysmonBaseConfig, sysmonModules)
	if err != nil {
		log.Fatal(err)
	}

	if generateRuleIds {
		err = sysmon.ReplaceRuleNamesWithID(sysmonBaseConfig)
		if err != nil {
			log.Fatal(err)
		}
	}

	if removeRuleNames {
		err = sysmon.RemoveRuleNames(sysmonBaseConfig)
		if err != nil {
			log.Fatal(err)
		}
	}

	//add header
	sysmonBaseConfig.Comment = " Generated by sysmoncfg(" + Version + ") at " + time.Now().Format("02.01.2006 15:04:05") + " "

	err = helper.SaveAsXML(cfg.OutFilename, sysmonBaseConfig)
	if err != nil {
		log.Fatal(err)
	}

	sysmonConfigHash, err := helper.CalcSha256sum(cfg.OutFilename)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Config successfully generated and saved to: " + cfg.OutFilename)
	fmt.Println("SHA256: " + sysmonConfigHash)
}
